version: 2
updates:
    - package-ecosystem: composer
      directory: '/'
      schedule:
          interval: monthly

    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly

    - package-ecosystem: composer
      directory: '/vendor-bin/php-codesniffer'
      schedule:
          interval: monthly

    - package-ecosystem: composer
      directory: '/vendor-bin/php-cs-fixer'
      schedule:
          interval: monthly

    - package-ecosystem: composer
      directory: '/vendor-bin/phpspec'
      schedule:
          interval: monthly

    - package-ecosystem: composer
      directory: '/vendor-bin/phpstan'
      schedule:
          interval: monthly

    - package-ecosystem: composer
      directory: '/vendor-bin/phpunit'
      schedule:
          interval: monthly
