dist: bionic

language: php
php:
    - '7.3'

env:
    global:
        - TZ=Europe/Paris
        - DATABASE_URL=pgsql://postgres@127.0.0.1:5432/symfony_app_template_test

cache:
    yarn: true
    directories:
        - vendor
        - node_modules
        - ~/.composer/cache/files
        - ~/.cache
        - ~/.nvm

notifications:
    email: false

addons:
    postgresql: '10'
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10
            # Cypress
            - libgconf-2-4
    hosts:
        - symfony-app-template.vm
        - www.symfony-app-template.vm

stages:
    - test

_cypress_job: &_cypress_job
    before_script:
        - make install-app@test
        - composer dump-autoload --optimize --classmap-authoritative
        - bin/console cache:warmup
        - yarn cypress install
        - APP_ENV=test php bin/console server:start
    after_script:
        - APP_ENV=test php bin/console server:stop

jobs:
    include:
        - stage: test
          name: Linting files, running basic tests (PHPStan, PHPUnit, phpspec), and Behat
        - name: Cypress
          <<: *_cypress_job
          if: type = pull_request AND head_branch !~ /^dependabot/
          script:
              - CI_BUILD_ID=$(head -200 /dev/urandom | cksum | cut -f1 -d " ")
              - yarn cypress run --record --ci-build-id $CI_BUILD_ID
        - name: Cypress for Dependabot
          <<: *_cypress_job
          if: type = pull_request AND head_branch =~ /^dependabot/
          script: yarn cypress run

before_install:
    # PHP
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo date.timezone = Europe/Paris >> $INI
    - echo memory_limit = -1 >> $INI
    - echo session.gc_probability = 0 >> $INI
    - echo extension=apcu.so >> $INI
    # https://symfony.com/doc/current/performance.html#use-the-opcache-byte-code-cache
    - echo opcache.enable = 1 >> $INI
    - echo opcache.enable_cli = 1 >> $INI
    # https://symfony.com/doc/current/performance.html#configure-opcache-for-maximum-performance
    - echo opcache.memory_consumption=256 >> $INI
    - echo opcache.max_accelerated_files=20000 >> $INI
    # https://symfony.com/doc/current/performance.html#don-t-check-php-files-timestamps
    - echo opcache.validate_timestamps=0 >> $INI
    # https://symfony.com/doc/current/performance.html#configure-the-php-realpath-cache
    - echo realpath_cache_size=4096K >> $INI
    - echo realpath_cache_ttl=600 >> $INI

    # Node
    - nvm install v10
    - nvm use 10
    - npm install --global yarn

install:
    # PHP/Composer
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install --no-interaction

    # Node/Yarn
    - yarn install --frozen-lockfile

before_script:
    - psql -c 'DROP DATABASE IF EXISTS symfony_app_template_test;' -U postgres
    - psql -c 'CREATE DATABASE symfony_app_template_test;' -U postgres

    # Bootstrap app
    - make install-app@test

script:
    - composer validate

    - bin/console lint:twig templates
    - bin/console lint:yaml config --parse-tags
    - bin/console api:swagger:export > /dev/null # trick to check if ApiPlatform is not correctly configured
    - bin/php-cs-fixer.phar fix --verbose --diff --dry-run src/
    - APP_ENV=test bin/console doctrine:schema:validate

    - yarn lint:js --no-fix
    - yarn lint:css --no-fix

    - php bin/phpstan.phar analyse src/
    - php bin/simple-phpunit
    - php bin/phpspec run

    # Behat
    - make install-app@test
    - bin/behat --format progress --tags '~@skip'
    - bin/behat --tags '@skip' || true # run skipped tests to not forgot them, and don't stop the build if it fails
