language: php
dist: trusty

php:
    - '7.3'

env:
    global:
        - TZ=Europe/Paris

        # If using MariaDB
        - DATABASE_URL=mysql://travis@127.0.0.1:3306/symfony_app_template_test
        - DATABASE_SERVER_VERSION=11.3

        # If using PostgreSQL (uncomment)
        #- DATABASE_URL=pgsql://postgres@127.0.0.1:5433/symfony_app_template_test
        #- DATABASE_SERVER_VERSION=11.3

cache:
    yarn: true
    directories:
        - vendor
        - node_modules
        - ~/.composer/cache/files
        - ~/.cache
        - ~/.nvm

notifications:
    email: false

addons:
    mariadb: '10.3'
    #postgresql: '11'
    apt:
        packages:
            #- postgresql-11
            #- postgresql-client-11
    hosts:
        - symfony-app-template.vm
        - www.symfony-app-template.vm

before_install:
    # PostgreSQL
    #- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
    #- sudo service postgresql restart
    #- sleep 1

    # PHP
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo date.timezone = Europe/Paris >> $INI
    - echo memory_limit = -1 >> $INI
    - echo session.gc_probability = 0 >> $INI
    - echo "extension=apcu.so >> $INI

    # Node
    - nvm install v10
    - nvm use 10
    - npm install --global yarn

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install --no-interaction --prefer-dist

script:
    - make install-app@test
    - composer validate
    # Node
    - yarn
    - yarn lint:js --no-fix
    - yarn lint:css --no-fix
    - yarn build:prod
    # PHP
    - APP_ENV=test bin/console doctrine:schema:validate
    - bin/console lint:twig templates
    - bin/console lint:yaml config --parse-tags
    - bin/php-cs-fixer fix --verbose --diff --dry-run src/
    - php bin/phpstan analyse src/
    - php bin/phpunit
    - php bin/phpspec run
    - bin/behat --format progress
    # Cypress, reset database before running it
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then make init-db@test; fi
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then yarn build:dev; fi
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then APP_ENV=test php bin/console server:start; fi
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then yarn cypress install; fi
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then yarn cypress run --config video=false; fi
    - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then APP_ENV=test php bin/console server:stop; fi
