controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_api:
    resource: ../../src/Controller/Api/
    type: annotation
    defaults:
        _format: json

controllers_debug:
    resource: ../../src/Controller/Debug/
    type: annotation
    prefix: _debug
    condition: '%kernel.debug% == true'
