services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/behat/bootstrap/*'

    App\Tests\Behat\ExtendedBehatchRestContext:
        autoconfigure: false
