version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "in_range" }
      - match: { dependency_type: "production", update_type: "semver:minor" }

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "auto"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "in_range" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
