name: Dependabot auto-approve & auto-merge
on:
    workflow_run:
        workflows: ['CI']
        types: [completed]

permissions:
    pull-requests: write
    contents: write

jobs:
    auto_approve_and_merge:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1.1.0
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Approve and merge the PR
              run: |
                  gh pr review --approve "$PR_URL"
                  gh pr merge --merge --delete-branch "$PR_URL"
              env:
                  PR_URL: '${{ github.event.pull_request.html_url }}'
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
